---
services:
  ark-server-dl:
    command:
      - "+force_install_dir"
      - "/data"
      - "+login"
      - "anonymous"
      - "+app_update"
      - "376030"
      - "+quit"
    container_name: ark-server-dl
    hostname: ark-server-dl
    image: steamcmd/steamcmd:ubuntu
    restart: "no"
    volumes:
      - "/root/.steam/logs:/var/log/steamcmd"
      - "/var/lib/ark-server:/data"

version: "3.9"
